name: SSH on Linux via Ngrok

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set SSH Password and Install ngrok
        run: |
          # Runner kullanıcısı için bir şifre belirle
          SSH_PASSWORD="password123"
          echo "runner:$SSH_PASSWORD" | sudo chpasswd
          echo "SSH password for user 'runner' is: $SSH_PASSWORD"
          
          # Ngrok'u indir ve kur
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
          tar -xvzf ngrok.tgz
          sudo mv ngrok /usr/local/bin/

      - name: Authenticate Ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: ngrok authtoken $NGROK_AUTH_TOKEN

      - name: Start Ngrok Tunnel for SSH
        run: |
          # Ngrok'u arka planda başlat ve SSH portuna (22) tünel aç
          nohup ngrok tcp 22 &
          
          # Ngrok API'sinin başlaması için bekle
          sleep 10
          
          # Ngrok API'sinden tünel adresini al ve yazdır
          # Bu komut, tam SSH komutunu sizin için oluşturur
          SSH_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url' | sed 's/tcp:\/\///')
          echo "=================================================================="
          echo "SSH BAĞLANTI KOMUTU:"
          echo "ssh runner@$SSH_URL"
          echo "Şifre: password123"
          echo "=================================================================="

      - name: Keep Workflow Alive
        run: |
          echo "SSH tüneli aktif. Kapatmak için workflow'u iptal edin."
          sleep 21000
